# Generated by Django 6.0.6 on 2026-06-16 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_is_bundle_bundleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='marketplace.product'),
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.PositiveIntegerField(help_text='Budget in UGX')),
                ('image', models.ImageField(blank=True, null=True, upload_to='requests/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests', to='marketplace.category')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together={('product', 'buyer', 'seller')},
        ),
        migrations.AddField(
            model_name='chatthread',
            name='item_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='marketplace.itemrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together={('item_request', 'buyer', 'seller'), ('product', 'buyer', 'seller')},
        ),
    ]
