# Generated by Django 6.0.6 on 2026-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_price',
            field=models.PositiveIntegerField(blank=True, help_text='Special price during Flash Sale Hour', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
