# Generated by Django 6.0.6 on 2026-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_product_flash_sale_price_product_is_flash_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('big_card', 'Big Hero Card'), ('flash_sales', 'Flash Sales Card'), ('requests', 'Requests Card'), ('bundles', 'Setup Bundles Card')], max_length=20)),
                ('image', models.ImageField(upload_to='banners/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display for big card slideshow')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
